In [4]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.9494000000953675 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.1                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2025.3                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [5]:
import  pandas as pd
df = pd.read_csv("Global ecological country.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Country                         188 non-null    str
 1   Region                          188 non-null    str
 2   Population (millions)           188 non-null    float64
 3   HDI                             172 non-null    float64
 4   GDP per Capita                  173 non-null    str
 5   Cropland Footprint              173 non-null    float64
 6   Grazing Footprint               169 non-null    float64
 7   Forest Footprint                171 non-null    float64
 8   Carbon Footprint                173 non-null    float64
 9   Fish Footprint                  172 non-null    float64
 10  Total Ecological Footprint      186 non-null    float64
 11  Cropland                        173 non-null    float64
 12  Grazing Land                    173 non-null    float64
 13  Forest Land                     169 non-null    float64
 14  Fishing Water                   173 non-null    float64
 15  Urban Land                      173 non-null    float64
 16  Total Biocapacity               188 non-null    float64
 17  Biocapacity Deficit or Reserve  188 non-null    float64
 18  Earths Required                 188 non-null    float64
 19  Countries Required              188 non-null    float64
 20  Data Quality                    188 non-null    str
dtypes: float64(17), str(4)
memory usage: 28.0 KB

In [6]:
df

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Cropland,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Data Quality
0,Afghanistan,Middle East/Central Asia,29.82,0.46,$614.66,0.30,0.20,0.08,0.18,0.00,...,0.24,0.20,0.02,0.00,0.04,0.50,-0.30,0.46,1.60,6
1,Albania,Northern/Eastern Europe,3.16,0.73,"$4,534.37",0.78,0.22,0.25,0.87,0.02,...,0.55,0.21,0.29,0.07,0.06,1.18,-1.03,1.27,1.87,6
2,Algeria,Africa,38.48,0.73,"$5,430.57",0.60,0.16,0.17,1.14,0.01,...,0.24,0.27,0.03,0.01,0.03,0.59,-1.53,1.22,3.61,5
3,Angola,Africa,20.82,0.52,"$4,665.91",0.33,0.15,0.12,0.20,0.09,...,0.20,1.42,0.64,0.26,0.04,2.55,1.61,0.54,0.37,6
4,Antigua and Barbuda,Latin America,0.09,0.78,"$13,205.10",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.94,-4.44,3.11,5.70,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,Viet Nam,Asia-Pacific,90.80,0.66,"$1,532.31",0.50,0.01,0.19,0.79,0.05,...,0.55,0.01,0.17,0.16,0.10,1.00,-0.65,0.95,1.66,6
184,Wallis and Futuna Islands,Asia-Pacific,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.51,-0.56,1.19,1.37,3T
185,Yemen,Middle East/Central Asia,23.85,0.50,"$1,302.30",0.34,0.14,0.04,0.42,0.04,...,0.09,0.12,0.04,0.20,0.04,0.50,-0.53,0.59,2.06,5
186,Zambia,Africa,14.08,0.58,"$1,740.64",0.19,0.18,0.33,0.24,0.01,...,0.24,0.94,0.99,0.02,0.04,2.23,1.24,0.57,0.44,6
187,Zimbabwe,Africa,13.72,0.49,$865.91,0.20,0.32,0.29,0.53,0.01,...,0.15,0.32,0.12,0.01,0.02,0.62,-0.75,0.79,2.20,6

In [9]:
df.mean(numeric_only=True)

Population (millions)             37.342372
HDI                                0.686360
Cropland Footprint                 0.578208
Grazing Footprint                  0.263373
Forest Footprint                   0.375556
Carbon Footprint                   1.770462
Fish Footprint                     0.121337
Total Ecological Footprint         3.325323
Cropland                           0.531850
Grazing Land                       0.456590
Forest Land                        2.497692
Fishing Water                      0.595145
Urban Land                         0.067110
Total Biocapacity                  4.019681
Biocapacity Deficit or Reserve     0.702074
Earths Required                    1.915745
Countries Required                 4.037397
dtype: float64

In [10]:
df.median(numeric_only=True)

Population (millions)             7.970
HDI                               0.720
Cropland Footprint                0.520
Grazing Footprint                 0.180
Forest Footprint                  0.260
Carbon Footprint                  1.110
Fish Footprint                    0.070
Total Ecological Footprint        2.740
Cropland                          0.350
Grazing Land                      0.120
Forest Land                       0.340
Fishing Water                     0.110
Urban Land                        0.050
Total Biocapacity                 1.310
Biocapacity Deficit or Reserve   -0.730
Earths Required                   1.580
Countries Required                1.705
dtype: float64

In [11]:
df.mode()

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Cropland,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required,Data Quality
0,Afghanistan,Africa,0.1,0.72,"$1,016.83",0.34,0.01,0.17,0.07,0.01,...,0.14,0.0,0.02,0.0,0.04,1.24,-1.46,0.7,0.72,5
1,Albania,NaN,NaN,NaN,"$1,062.11",0.43,0.03,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.32,NaN,1.25,NaN
2,Algeria,NaN,NaN,NaN,"$1,079.27",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.40,NaN
3,Angola,NaN,NaN,NaN,"$1,116.37",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Antigua and Barbuda,NaN,NaN,NaN,"$1,117.58",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,Viet Nam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,Wallis and Futuna Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.describe()

,Population (millions),HDI,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,Total Ecological Footprint,Cropland,Grazing Land,Forest Land,Fishing Water,Urban Land,Total Biocapacity,Biocapacity Deficit or Reserve,Earths Required,Countries Required
count,188.000000,172.00000,173.000000,169.000000,171.000000,173.000000,172.000000,186.000000,173.000000,173.000000,169.000000,173.000000,173.000000,188.000000,188.000000,188.000000,188.000000
mean,37.342372,0.68636,0.578208,0.263373,0.375556,1.770462,0.121337,3.325323,0.531850,0.456590,2.497692,0.595145,0.067110,4.019681,0.702074,1.915745,4.037397
std,140.756836,0.15604,0.355691,0.355606,0.360025,1.903892,0.160893,2.374500,0.672567,1.014738,10.715548,1.661872,0.054844,11.689075,11.771339,1.369624,12.444616
min,0.000000,0.34000,0.070000,0.000000,0.010000,-1.500000,-0.230000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,-14.140000,0.240000,0.020000
25%,2.037500,0.55750,0.350000,0.080000,0.170000,0.380000,0.020000,1.495000,0.180000,0.030000,0.060000,0.030000,0.030000,0.675000,-1.935000,0.855000,0.942500
50%,7.970000,0.72000,0.520000,0.180000,0.260000,1.110000,0.070000,2.740000,0.350000,0.120000,0.340000,0.110000,0.050000,1.310000,-0.730000,1.580000,1.705000
75%,24.870000,0.80250,0.700000,0.320000,0.460000,2.580000,0.150000,4.700000,0.590000,0.340000,1.140000,0.370000,0.090000,2.815000,0.212500,2.677500,2.847500
max,1408.040000,0.94000,2.680000,3.470000,3.030000,12.650000,0.820000,15.820000,5.420000,8.230000,95.160000,16.070000,0.270000,111.350000,109.010000,9.140000,159.470000

In [16]:
df.loc[:,'HDI'].mean()

np.float64(0.6863595697674418)

In [17]:
df.mean(axis=1,numeric_only=True)[0:4]

0    2.034706
1    0.747647
2    2.816471
3    1.811176
dtype: float64

In [19]:
df.std(numeric_only=True)

Population (millions)             140.756836
HDI                                 0.156040
Cropland Footprint                  0.355691
Grazing Footprint                   0.355606
Forest Footprint                    0.360025
Carbon Footprint                    1.903892
Fish Footprint                      0.160893
Total Ecological Footprint          2.374500
Cropland                            0.672567
Grazing Land                        1.014738
Forest Land                        10.715548
Fishing Water                       1.661872
Urban Land                          0.054844
Total Biocapacity                  11.689075
Biocapacity Deficit or Reserve     11.771339
Earths Required                     1.369624
Countries Required                 12.444616
dtype: float64

In [21]:
df.std(axis=1,numeric_only=True)[0:6]

0    7.172289
1    0.980399
2    9.253179
3    4.944023
4    3.493558
5    9.710764
dtype: float64

In [23]:
df_u = df.rename(columns={'HDI': 'ABC'}, inplace=False)

In [24]:
df_u.groupby(['Region']).ABC.mean()

Region
Africa                      0.515714
Asia-Pacific                0.687500
European Union              0.864615
Latin America               0.720433
Middle East/Central Asia    0.726957
North America               0.910000
Northern/Eastern Europe     0.788333
Name: ABC, dtype: float64

In [27]:
!mamba install scikit-learn

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas, scikit-learn
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 5.210699999928474 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ brotli-python                 1.2.0                         py313h33caa6c_0               emscripten-forge
+ certifi                       2026.1.4                      pyhd8ed1ab_0                  conda-forge
+ charset-normalizer            3.4.4                         pyhd8ed1ab_0                  conda-forge
+ idna                          3.11                          pyhd8ed1ab_0                  conda-forge
+ joblib                        1.5.3                         py313h1804a44_1               emscripten-forge
+ pysocks                       1.7.1                         py313h1804a44_2               emscripten-forge
+ requests                      2.32.5                        pyhcf101f3_1                  conda-forge
+ scikit-learn                  1.8.0                         np22py313h2c67255_3           emscripten-forge
+ setuptools                    82.0.0                        pyh332efcf_0                  conda-forge
+ threadpoolctl                 3.6.0                         pyhecae5ae_0                  conda-forge
+ urllib3                       2.2.2                         pyhd8ed1ab_0                  conda-forge

In [28]:
from sklearn import preprocessing

In [29]:
from sklearn import preprocessing

enc = preprocessing.OneHotEncoder()

enc_df = pd.DataFrame(enc.fit_transform(df[['Region']]).toarray())

enc_df

       0    1    2    3    4    5    6
0    0.0  0.0  0.0  0.0  1.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0  0.0  1.0
2    1.0  0.0  0.0  0.0  0.0  0.0  0.0
3    1.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  1.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...
183  0.0  1.0  0.0  0.0  0.0  0.0  0.0
184  0.0  1.0  0.0  0.0  0.0  0.0  0.0
185  0.0  0.0  0.0  0.0  1.0  0.0  0.0
186  1.0  0.0  0.0  0.0  0.0  0.0  0.0
187  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[188 rows x 7 columns]

In [30]:
df_encode = df.join(enc_df)

df_encode

,Country,Region,Population (millions),HDI,GDP per Capita,Cropland Footprint,Grazing Footprint,Forest Footprint,Carbon Footprint,Fish Footprint,...,Earths Required,Countries Required,Data Quality,0,1,2,3,4,5,6
0,Afghanistan,Middle East/Central Asia,29.82,0.46,$614.66,0.30,0.20,0.08,0.18,0.00,...,0.46,1.60,6,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,Albania,Northern/Eastern Europe,3.16,0.73,"$4,534.37",0.78,0.22,0.25,0.87,0.02,...,1.27,1.87,6,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Algeria,Africa,38.48,0.73,"$5,430.57",0.60,0.16,0.17,1.14,0.01,...,1.22,3.61,5,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Angola,Africa,20.82,0.52,"$4,665.91",0.33,0.15,0.12,0.20,0.09,...,0.54,0.37,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Antigua and Barbuda,Latin America,0.09,0.78,"$13,205.10",NaN,NaN,NaN,NaN,NaN,...,3.11,5.70,2,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,Viet Nam,Asia-Pacific,90.80,0.66,"$1,532.31",0.50,0.01,0.19,0.79,0.05,...,0.95,1.66,6,0.0,1.0,0.0,0.0,0.0,0.0,0.0
184,Wallis and Futuna Islands,Asia-Pacific,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.19,1.37,3T,0.0,1.0,0.0,0.0,0.0,0.0,0.0
185,Yemen,Middle East/Central Asia,23.85,0.50,"$1,302.30",0.34,0.14,0.04,0.42,0.04,...,0.59,2.06,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0
186,Zambia,Africa,14.08,0.58,"$1,740.64",0.19,0.18,0.33,0.24,0.01,...,0.57,0.44,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0
187,Zimbabwe,Africa,13.72,0.49,$865.91,0.20,0.32,0.29,0.53,0.01,...,0.79,2.20,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0