In [2]:
import pandas as pd
df=pd.read_csv("ecomerce.csv")
df

,user_id,age,gender,country,urban_rural,income_level,employment_status,education_level,relationship_status,has_children,...,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,last_purchase_date,social_sharing_frequency,premium_subscription,return_rate
0,1,56,Female,Germany,Suburban,90860,Self-employed,Associate Degree,Single,0,...,10.0,2.0,62.0,7.0,74.0,19.0,2025-06-22,6.0,1.0,50.0
1,2,69,Male,Japan,Suburban,35423,Unemployed,Bachelor,Single,1,...,5.0,7.0,54.0,5.0,23.0,8.0,2026-07-25,3.0,0.0,37.0
2,3,46,Female,India,Urban,21467,Self-employed,Associate Degree,Married,1,...,3.0,3.0,33.0,7.0,12.0,13.0,2026-02-26,6.0,0.0,53.0
3,4,32,Male,Canada,Urban,41770,Self-employed,Bachelor,Widowed,0,...,5.0,9.0,26.0,4.0,19.0,9.0,2026-10-27,7.0,0.0,98.0
4,5,60,Female,Japan,Urban,183882,Employed,Associate Degree,Widowed,1,...,8.0,0.0,18.0,7.0,30.0,3.0,2026-06-23,3.0,0.0,86.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145909,145910,74,Female,Canada,Urban,156002,Employed,High School,Married,0,...,3.0,9.0,50.0,1.0,71.0,2.0,2025-02-27,5.0,1.0,84.0
145910,145911,64,Male,Canada,Suburban,20492,Employed,High School,Divorced,0,...,9.0,2.0,88.0,0.0,44.0,2.0,2026-11-23,2.0,0.0,47.0
145911,145912,19,Female,France,Suburban,18738,Employed,Master,Married,0,...,6.0,1.0,73.0,4.0,12.0,22.0,2026-06-28,8.0,1.0,48.0
145912,145913,53,Male,Canada,Rural,95892,Retired,Bachelor,In a relationship,0,...,1.0,8.0,28.0,6.0,17.0,2.0,2026-06-17,1.0,0.0,45.0
145913,145914,46,Female,UK,Urban,126519,Unemployed,Bachelor,Divorced,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe()

,user_id,age,income_level,has_children,household_size,weekly_purchases,monthly_spend,cart_abandonment_rate,review_writing_frequency,average_order_value,...,wishlist_items_count,cart_items_average,checkout_abandonments_per_month,purchase_conversion_rate,app_usage_frequency,notification_response_rate,account_age_months,social_sharing_frequency,premium_subscription,return_rate
count,145914.000000,145914.000000,145914.000000,145914.000000,145914.000000,145914.000000,145914.000000,145914.000000,145914.000000,145913.000000,...,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000,145913.000000
mean,72957.500000,49.023329,105161.305968,0.400510,5.504468,9.988603,2502.998102,40.243787,3.446462,255.257078,...,10.006757,5.486249,4.992420,49.952574,3.497639,50.022184,12.482740,3.595094,0.359029,50.008094
std,42121.887927,18.158512,54900.977280,0.490003,2.875569,6.055555,1447.001489,25.462565,1.853902,141.508901,...,6.060582,2.868925,3.159085,29.146629,2.292053,29.141379,6.918553,1.935760,0.479717,29.144552
min,1.000000,18.000000,10000.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,10.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,36479.250000,33.000000,57607.000000,0.000000,3.000000,5.000000,1248.000000,18.000000,2.000000,133.000000,...,5.000000,3.000000,2.000000,25.000000,2.000000,25.000000,7.000000,2.000000,0.000000,25.000000
50%,72957.500000,49.000000,105226.000000,0.000000,6.000000,10.000000,2508.000000,40.000000,3.000000,256.000000,...,10.000000,5.000000,5.000000,50.000000,3.000000,50.000000,12.000000,4.000000,0.000000,50.000000
75%,109435.750000,65.000000,152921.750000,1.000000,8.000000,15.000000,3758.000000,62.000000,5.000000,378.000000,...,15.000000,8.000000,8.000000,75.000000,5.000000,75.000000,18.000000,5.000000,1.000000,75.000000
max,145914.000000,80.000000,199999.000000,1.000000,10.000000,20.000000,5000.000000,90.000000,8.000000,500.000000,...,20.000000,10.000000,10.000000,100.000000,7.000000,100.000000,24.000000,8.000000,1.000000,100.000000

In [4]:
df.index

RangeIndex(start=0, stop=145914, step=1)

In [5]:
df.columns

Index(['user_id', 'age', 'gender', 'country', 'urban_rural', 'income_level',
       'employment_status', 'education_level', 'relationship_status',
       'has_children', 'household_size', 'occupation', 'ethnicity',
       'language_preference', 'device_type', 'weekly_purchases',
       'monthly_spend', 'cart_abandonment_rate', 'review_writing_frequency',
       'average_order_value', 'preferred_payment_method',
       'coupon_usage_frequency', 'loyalty_program_member', 'referral_count',
       'product_category_preference', 'shopping_time_of_day',
       'weekend_shopper', 'impulse_purchases_per_month', 'browse_to_buy_ratio',
       'return_frequency', 'budgeting_style', 'brand_loyalty_score',
       'impulse_buying_score', 'environmental_consciousness',
       'health_conscious_shopping', 'travel_frequency', 'hobby_count',
       'social_media_influence_score', 'reading_habits', 'exercise_frequency',
       'stress_from_financial_decisions', 'overall_stress_level',
       'sleep_quality', 'physical_activity_level', 'mental_health_score',
       'daily_session_time_minutes', 'product_views_per_day',
       'ad_views_per_day', 'ad_clicks_per_day', 'wishlist_items_count',
       'cart_items_average', 'checkout_abandonments_per_month',
       'purchase_conversion_rate', 'app_usage_frequency',
       'notification_response_rate', 'account_age_months',
       'last_purchase_date', 'social_sharing_frequency',
       'premium_subscription', 'return_rate'],
      dtype='object')

In [6]:
df.shape

(145914, 60)

In [7]:
df.dtypes

user_id                              int64
age                                  int64
gender                              object
country                             object
urban_rural                         object
income_level                         int64
employment_status                   object
education_level                     object
relationship_status                 object
has_children                         int64
household_size                       int64
occupation                          object
ethnicity                           object
language_preference                 object
device_type                         object
weekly_purchases                     int64
monthly_spend                        int64
cart_abandonment_rate                int64
review_writing_frequency             int64
average_order_value                float64
preferred_payment_method            object
coupon_usage_frequency             float64
loyalty_program_member             float64
referral_count                     float64
product_category_preference         object
shopping_time_of_day                object
weekend_shopper                    float64
impulse_purchases_per_month        float64
browse_to_buy_ratio                float64
return_frequency                   float64
budgeting_style                     object
brand_loyalty_score                float64
impulse_buying_score               float64
environmental_consciousness        float64
health_conscious_shopping          float64
travel_frequency                   float64
hobby_count                        float64
social_media_influence_score       float64
reading_habits                     float64
exercise_frequency                 float64
stress_from_financial_decisions    float64
overall_stress_level               float64
sleep_quality                      float64
physical_activity_level            float64
mental_health_score                float64
daily_session_time_minutes         float64
product_views_per_day              float64
ad_views_per_day                   float64
ad_clicks_per_day                  float64
wishlist_items_count               float64
cart_items_average                 float64
checkout_abandonments_per_month    float64
purchase_conversion_rate           float64
app_usage_frequency                float64
notification_response_rate         float64
account_age_months                 float64
last_purchase_date                  object
social_sharing_frequency           float64
premium_subscription               float64
return_rate                        float64
dtype: object

In [8]:
df.columns.values

array(['user_id', 'age', 'gender', 'country', 'urban_rural',
       'income_level', 'employment_status', 'education_level',
       'relationship_status', 'has_children', 'household_size',
       'occupation', 'ethnicity', 'language_preference', 'device_type',
       'weekly_purchases', 'monthly_spend', 'cart_abandonment_rate',
       'review_writing_frequency', 'average_order_value',
       'preferred_payment_method', 'coupon_usage_frequency',
       'loyalty_program_member', 'referral_count',
       'product_category_preference', 'shopping_time_of_day',
       'weekend_shopper', 'impulse_purchases_per_month',
       'browse_to_buy_ratio', 'return_frequency', 'budgeting_style',
       'brand_loyalty_score', 'impulse_buying_score',
       'environmental_consciousness', 'health_conscious_shopping',
       'travel_frequency', 'hobby_count', 'social_media_influence_score',
       'reading_habits', 'exercise_frequency',
       'stress_from_financial_decisions', 'overall_stress_level',
       'sleep_quality', 'physical_activity_level', 'mental_health_score',
       'daily_session_time_minutes', 'product_views_per_day',
       'ad_views_per_day', 'ad_clicks_per_day', 'wishlist_items_count',
       'cart_items_average', 'checkout_abandonments_per_month',
       'purchase_conversion_rate', 'app_usage_frequency',
       'notification_response_rate', 'account_age_months',
       'last_purchase_date', 'social_sharing_frequency',
       'premium_subscription', 'return_rate'], dtype=object)

In [9]:
df.iloc[100]

user_id                                          101
age                                               61
gender                                        Female
country                                        China
urban_rural                                 Suburban
income_level                                   41317
employment_status                         Unemployed
education_level                     Associate Degree
relationship_status                In a relationship
has_children                                       1
household_size                                     4
occupation                                        IT
ethnicity                           African American
language_preference                            Hindi
device_type                                   Mobile
weekly_purchases                                  12
monthly_spend                                   1418
cart_abandonment_rate                             43
review_writing_frequency                           1
average_order_value                            418.0
preferred_payment_method                      PayPal
coupon_usage_frequency                           3.0
loyalty_program_member                           1.0
referral_count                                   1.0
product_category_preference                    Books
shopping_time_of_day                       Afternoon
weekend_shopper                                  0.0
impulse_purchases_per_month                      5.0
browse_to_buy_ratio                             13.0
return_frequency                                 3.0
budgeting_style                             Moderate
brand_loyalty_score                              0.0
impulse_buying_score                             6.0
environmental_consciousness                      7.0
health_conscious_shopping                        1.0
travel_frequency                                 4.0
hobby_count                                      1.0
social_media_influence_score                     5.0
reading_habits                                   8.0
exercise_frequency                               3.0
stress_from_financial_decisions                  5.0
overall_stress_level                             4.0
sleep_quality                                    7.0
physical_activity_level                          4.0
mental_health_score                              6.0
daily_session_time_minutes                      69.0
product_views_per_day                            3.0
ad_views_per_day                                 8.0
ad_clicks_per_day                                1.0
wishlist_items_count                            17.0
cart_items_average                               1.0
checkout_abandonments_per_month                  4.0
purchase_conversion_rate                        12.0
app_usage_frequency                              5.0
notification_response_rate                      61.0
account_age_months                              18.0
last_purchase_date                        2025-11-20
social_sharing_frequency                         1.0
premium_subscription                             1.0
return_rate                                      4.0
Name: 100, dtype: object

In [10]:
df.columns.names

FrozenList([None])

In [11]:
df.iloc[:100,2:5]

    gender  country urban_rural
0   Female  Germany    Suburban
1     Male    Japan    Suburban
2   Female    India       Urban
3     Male   Canada       Urban
4   Female    Japan       Urban
..     ...      ...         ...
95  Female       UK       Rural
96  Female      USA    Suburban
97  Female      USA    Suburban
98    Male    India    Suburban
99  Female    Japan       Urban

[100 rows x 3 columns]

In [12]:
df.iloc[:5,1:4]

   age  gender  country
0   56  Female  Germany
1   69    Male    Japan
2   46  Female    India
3   32    Male   Canada
4   60  Female    Japan

In [13]:
df.CreditScore.min()

<class 'AttributeError'>: 'DataFrame' object has no attribute 'CreditScore'

In [14]:
df.age.min()

np.int64(18)

In [15]:
df.head[5]

<class 'TypeError'>: 'method' object is not subscriptable